# ConduitSpawnStopper configuration

# How many ticks between automatic saves of placed conduits to file (default: 6000 = 5 minutes)
# Saves on disable as well, but if server crashes recently placed/removed conduits will be out of sync
# Replace a conduit on that block to fix any issues
autosave-ticks: 6000

# How many chunks away to check for conduits (default: 2 = 5x5 chunk grid around conduit)
# 0 would be just the chunk the conduit is in it's in
chunk-check-radius: 2

# Enable debug logging for all drowned spawn events (default: false)
debug: false
