# DrownedConduitSpawnBlocker configuration

# How many chunks away to check for conduits (default: 2 = 5x5 chunk grid around conduit)
# 0 would be just the chunk the conduit is in
chunk-check-radius: 2

## How often to save placed conduits to conduits.yml
# If set to 0 or below, saves instantly (asynchronously) whenever a conduit is placed or removed
# If above 0, saves every N ticks (default: 6000 = 5 minutes)
# conduits.yml saves on disable as well, but if server crashes recently placed/removed conduits will be out of sync
# Place a conduit on that block to fix any syncing issues
autosave-ticks: 6000

# Enable debug logging for all drowned spawn events (will spam your console)
debug: false
