name: ConduitSpawnStopper
main: com.example.conduitstopper.ConduitSpawnStopper
version: ${project.version}
api-version: 1.21
commands: {}
description: "Stops drowned from spawning when conduits are nearby."
authors: ["Carter4242"]
