name: DrownedConduitSpawnBlocker
main: com.carter4242.conduitblocker.DrownedConduitSpawnBlocker
version: ${project.version}
api-version: 1.20
commands: {}
description: 'Stops drowned from spawning when there is a conduit within a configurable chunk range are nearby.'
authors: ['Carter4242']
